networks:
  linqra-network:
    external: true

services:
  komunas-app:
    container_name: komunas-app
    build:
      context: .
      dockerfile: ./.kube/komunas/Dockerfile.polaris
    environment:
      SPRING_PROFILES_ACTIVE: ec2
      CLIENT_TRUST_STORE: /app/client-truststore.jks
      CLIENT_TRUST_STORE_PASSWORD: 123456
      CLIENT_KEY_STORE: /app/client-keystore.jks
      CLIENT_KEY_STORE_PASSWORD: 123456
      CLIENT_ALIAS_NAME: komunas-app-container
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
      EUREKA_INSTANCE_URL: komunas-app
      GATEWAY_SERVICE_URL: api-gateway-service
      MONGO_DB_URI: ${MONGO_DB_URI}
    ports:
      - "8082:8082"
    networks:
      - linqra-network
    volumes:
      - ./:/app/komunas-app
      - ./keys:/app/keys
